### PR TITLE
Massive Update...

### PR DESCRIPTION
**Pull request by gordon-matt**
- Updated to .NET 6
- Updated NuGet packages
- Updated Krypton Toolkit to use latest NuGet package instead of DLLs that were there.
- Fix to support curly single quotes in addition to the straight ones, in ColumnIfTypeExpression
- Some UI improvements
- After clicking "Generate", the app will automatically show the "Results" page
- After clicking "New Template" or "Open Template", the app will automatically show the "Template" page
- Replaced a lot of the code in `DataAccessProviderFactory` with NET's own DbProviderFactory.
- Tons of refactoring
- Added fixes from other forks. Most notably from @houwenlong789.
- Added documentation to README.md
- Added new TablesExpression, for looping over tables
- Added Documentation Window (when clicking Help -> Documentation)
- Ensure disposable objects are actually disposed
- Probably some other things I forgot..

Enjoy!

### CODE REVIEW

**Comment by gordon-matt** [comment]
@victoryoalli I see you haven't worked on this project since 2015 and the last merge was my pull request (#1) from 2017 (which was only merged in 2018 - 1.5 years after the PR was raised). If you're no longer supporting this project and if you're okay with it, I'd be happy to take ownership of it to continue the development, while still crediting the original work to your name and keep links to https://viento.digital/ in both the README.md and in the About window. What do you think?

**Comment by victoryoalli** [comment]
@gordon-matt, yes, it is a massive update, can wait to checkout.

About what you are proposing, it is hard to let go of your baby for many years. 

What I suggest is to start working on it together. Give you full access to the repository, and from there, we can see how it goes; what do you think?

**Comment by gordon-matt** [comment]
Hi @victoryoalli. Yes, I understand your feeling perfectly well. I've just accepted your invitation to collaborate. Thank you.

**Comment by gordon-matt** [comment]
Merged. Let me know what you think of the update and if you have any more suggestions.

**Pull request merged**
